### ISSUE TITLE
Default concrete type of `TopicConsumer` deserializer should be `Type[Deserializer]`

### ISSUE THREAD

**Issue by CJSmith-0141** [RegioHelden/django-kafka#31]
[see here](https://github.com/RegioHelden/django-kafka/blob/c5d4517af1556a3758dcdde9681530cd1158d331/django_kafka/topic/__init__.py#L93-L95) for (what I think is) an error. This isn't a problem with `AvroTopicConsumer` because the getter is being overridden instead of the class member. 

https://github.com/RegioHelden/django-kafka/blob/c5d4517af1556a3758dcdde9681530cd1158d331/django_kafka/topic/avro.py#L50C36-L59

If you agree this is incorrect, I will submit a PR with the fix.

**Comment by bodja** [comment]
Yes you are right, this has to be `StringDeserializer`. Go ahead with the PR. And thank you for contributing to the proj.
